#!/bin/bash

rm -rf tmp
mkdir -p tmp/src/net/sf/statcvs/output

cp -a src/net/sf/statcvs/model/ src/net/sf/statcvs/input/
src/net/sf/statcvs/util/ tmp/src/net/sf/statcvs
cp src/net/sf/statcvs/output/*Integration.java
tmp/src/net/sf/statcvs/output

find tmp/ -name "*.class" -or -name "CVS" -exec rm -rf {} \;

cd tmp && cvs -d squig@cvs.statcvs-xml.berlios.de:/cvsroot/statcvs-xml
import -ko statcvs-xml2 statcvs statcvs-`date +%Y%m%d`
